# Generated by Django 3.1.6 on 2021-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=1000, max_digits=1000, null=True),
        ),
    ]
