# Generated by Django 3.1.6 on 2021-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_auto_20210217_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sold_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
